server:
  port: 8082

spring:
  application:
  name: simple-rest-yml

datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  username: sa
  password: password

jpa:
  show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG