server:
    port: 8084

spring:
    application:
        name: simplesoapyml
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: sa
        password: password
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console

jpa:
    show-sql: true

logging:
    level:
        org.hibernate.SQL: DEBUG
        org.springframework.ws.client.MessageTracing.sent: DEBUG  # Log outgoing SOAP requests
        org.springframework.ws.client.MessageTracing.received: DEBUG  # Log incoming SOAP responses
        org.springframework.ws.server.endpoint: DEBUG  # Log SOAP server requests and responses
        org.springframework.ws.soap: DEBUG  # Log SOAP-specific actions
        org.springframework.ws.client: DEBUG  # Log SOAP client interactions
        org.springframework.oxm.jaxb: DEBUG  # Logs de JAXB (marshaller/unmarshaller)