
package org.xuaxpedia.springboot.soa.rest.simplesoapclient.wsdl;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "DemoDataPort", targetNamespace = "http://www.xuaxpedia.org/springboot/soa/soap/simplesoapyml/xml")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemoDataPort {


    /**
     * 
     * @param createDataXmlRequest
     */
    @WebMethod(operationName = "CreateDataXml")
    @Oneway
    public void createDataXml(
        @WebParam(name = "CreateDataXmlRequest", targetNamespace = "http://www.xuaxpedia.org/springboot/soa/soap/simplesoapyml/xml", partName = "CreateDataXmlRequest")
        CreateDataXmlRequest createDataXmlRequest);

    /**
     * 
     * @param getDataXmlRequest
     */
    @WebMethod(operationName = "GetDataXml")
    @Oneway
    public void getDataXml(
        @WebParam(name = "GetDataXmlRequest", targetNamespace = "http://www.xuaxpedia.org/springboot/soa/soap/simplesoapyml/xml", partName = "GetDataXmlRequest")
        GetDataXmlRequest getDataXmlRequest);

}
